<?php

/**
 * Custom callback from blocks section
 * Called from block named "video library name post menu"
 * return string
**/
function getName_channel() {

    $tid = arg(2);
    $term = taxonomy_term_load($tid);
    $term_name = $term->name;
    if(function_exists('get_color_channel')) {
        $color = get_color_channel($tid);
    }
    
    if($color == '') {
        $color = '#000';
    }
    $resource_check = $term->field_resources_link['und'][0]['value'];
    $resource_url = $term->field_resources_url['und'][0]['value'];
        
    $output .= '<div class ="post-menu-strip">';
    $output .= '<span class="lib-name inline-block float-left mstrip" style="color:'.$color.'">'.$term_name.'</span>';
    $output .= '<span class="default inline-block float-left mstrip">'.flag_create_link('default', $tid).'</span>';
    if($resource_check == 1) {
        $output .= '<span class="resources inline-block float-left mstrip">'.
                    l("> Resources",$resource_url,array('attributes'=>array('target'=>'_blank'))).'</span>';
    }
    $output .= '</div>';
    
    return $output;
}


/**
 * Custom callback for fetching the main color
 * @param $tid
 * return string
**/
function get_color_channel($tid) {
    $term = taxonomy_term_load($tid);
    $color = $term->field_color_title['und'][0]['rgb'];
    
    return $color;
}

/**
 * Custom Callback for displaying admin link for maanging channel
 * Called from block with id 54
 * return string
**/
function get_manage_channel_block() {
    $output = '';
    if(isset($_GET['channel_tid'])) {
        $options = array(
            'query' => array('channel_tid'=>$_GET['channel_tid']),
        );
        $output .= '<ul>';
        $output .= '<li>' . l("Manage Videos",'admin/manage-videos',$options) . '</li>';
        $output .= '<li>' . l("Manage Featured Videos",'admin/structure/nodequeue/8',$options) . '</li>';
        $output .= '<li>' . l("Manage Categories",'admin/structure/taxonomy/channel_categories',$options) . '</li>';
        $output .= '<li>' . l("Manage Tags",'admin/structure/taxonomy/channel_tags',$options) . '</li>';
        $output .= '</ul>';
    }
    
    return $output;
}

/**
 * Custom Callback for displaying admin link for tracking user report
 * Called from block with id 55
 * return string
**/
function get_manage_report_block() {
    $output = '';
    if(isset($_GET['channel_tid'])) {
        $options = array(
            'query' => array('channel_tid'=>$_GET['channel_tid']),
        );
        $channel_name = strtolower(get_channel_name_from_tid($_GET['channel_tid']));
        $output .= '<ul>';
        $output .= '<li>' . l("User Statistics",'admin/user-stat') . '</li>';
        $output .= '<li>' . l("Video Statistics",'admin/analytics',$options) . '</li>';
        $output .= '<li>' . l("File Download Statistics",'admin/downloads/reports',$options) . '</li>';
        $output .= '</ul>';
    }
    
    return $output;
}

/**
 * Custom callback for getting the type of node
 * Called in user_top_menu_link() in videolibrary_core.module file
 * @param $nid
 * return string
**/
function get_node_type($nid) {
    $type = db_query("SELECT type FROM node WHERE nid=:nid",array(':nid'=>$nid))->fetchField();
    return $type;
}

/**
 * Custom Callback for getting channel id from a node relation
 * Called from user_top_menu_link() in videolibrary_core.module file
 * @param $nid
 * return int
**/
function get_channel_tid_from_node($nid) {
    $channel_tid = db_query("SELECT field_library_tid FROM field_data_field_library WHERE entity_id=:nid",
                            array(':nid'=>$nid))->fetchField();
    return $channel_tid;
}

/**
 * Custom Callback for displaying download button at admin download statistics page
 * and show page title wrt channel name
 * Called from view named downloads
 * return string
**/
function get_download_report_title_and_button($link) {
    $output = '';
    
    if(isset($_GET['channel_tid'])) {
        if(function_exists('get_channel_name_from_tid')) {
            $channel_name = get_channel_name_from_tid($_GET['channel_tid']);
        }
       $output .= '<h4>' . $channel_name . t(" Download Statistics"). '</h4>';
    }
    $output .= '<p class="download-user-stats">'. l("Download",$link).'</p>';
    
    return $output;
}

/**
 * Custom callback to get channel name from tid passed in arguments
 * @param $ch_tid
 * return string
**/
function get_channel_name_from_tid($ch_tid) {
    if($ch_tid != '') {
       $channel_tid = $ch_tid;
       $term = taxonomy_term_load($channel_tid);
       $channel_name = $term->name;
    }
    
    return $channel_name;
}