<?php

/**
 * Custom callback from blocks section
 * Called from block named "video library name post menu"
 * return string
**/
function getName_channel() {

    $tid = arg(2);
    $term = taxonomy_term_load($tid);
    $term_name = $term->name;
    $color = get_color_channel($tid);
    
    $resource_check = $term->field_resources_link['und'][0]['value'];
    $resource_url = $term->field_resources_url['und'][0]['value'];
        
    $output .= '<div class ="post-menu-strip">';
    $output .= '<span class="lib-name inline-block float-left mstrip" style="color:'.$color.'">'.$term_name.'</span>';
    $output .= '<span class="default inline-block float-left mstrip">'.flag_create_link('default', $tid).'</span>';
    if($resource_check == 1) {
        $output .= '<span class="resources inline-block float-left mstrip">'.
                    l("> Resources",$resource_url).'</span>';
    }
    $output .= '</div>';
    
    return $output;
}


/**
 * Custom callback for fetching the main color
 * @param $tid
 * return string
**/
function get_color_channel($tid) {
    $term = taxonomy_term_load($tid);
    $color = $term->field_color_title['und'][0]['rgb'];
    
    return $color;
}

/**
 * Custom Callback for displaying admin link for maanging channel
 * Called from block with id 55
 * return string
**/
function get_manage_channel_block() {
    $output = '';
    if(isset($_GET['channel_tid'])) {
        $options = array(
            'query' => array('channel_tid'=>$_GET['channel_tid']),
        );
        $output .= '<ul>';
        $output .= '<li>' . l("Manage Videos",'admin/manage-videos',$options) . '</li>';
        $output .= '<li>' . l("Manage Featured Videos",'admin/structure/nodequeue/8',$options) . '</li>';
        $output .= '<li>' . l("Manage Categories",'admin/structure/taxonomy/channel_categories',$options) . '</li>';
        $output .= '<li>' . l("Manage Tags",'admin/structure/taxonomy/channel_tags',$options) . '</li>';
        $output .= '</ul>';
    }
    
    return $output;
}