<?php


/**
 * Implementation of the hook_block_info
 * return array
**/
function dynamic_channel_block_info() {
    $blocks['channel_name'] = array(
        'info' => t('Channel Name'),
        'region' => 'secondary',
        'status' => TRUE,
    );
    
    return $blocks;
}

/**
 * Implementation of the hook_block_view
 * return array
**/
function dynamic_channel_block_view($delta = '') {
    $block = array();
    
    switch($delta) {
        case 'channel_name':
            $block['content'] = getName_channel();
            break;
    }
    
    return $block;
}

/**
 * Custom callback from hook_block_view
 * return string
**/
function getName_channel() {
    $tid = arg(2);
    $term = taxonomy_term_load($tid);
    $term_name = $term->name;
    $color = get_color_channel($tid);
    
    $resource_check = $term->field_resource_link['und'][0]['value'];
    $resource_url = $term->field_resource_url['und'][0]['value'];
        
    $output = '<div class ="post-menu-strip">';
    $output .= '<span class="lib-name inline-block float-left mstrip" style="color:'.$color.'">'.$term_name.'</span>';
    if($resource_check == 1) {
        $output .= '<span class="resources inline-block float-left mstrip">'.
                    l("> Resources",$resource_url).'</span>';
    }
    $output .= '</div>';
    
    return $output;
}


/**
 * Custom callback for getting color of a channel chosen
**/
function get_color_channel($tid) {

    $term = taxonomy_term_load($tid);
    $term_name = $term->name;
    
    $all_fields_info = field_info_fields();
    $allowed_values= list_allowed_values($all_fields_info["field_color"]);
    $color = $allowed_values[$term->field_color['und'][0]['value']];
    
    return $color;
}

function get_latest_section_block($title,$nid) {
    $output = '';
    $tid = arg(2);
    $color = get_color_channel($tid);
    $output .= '<div class="latest_wrapper">
                <span class="latest_label" style="background-color:'.$color.'">Latest Videos</span>
                <span class="latest_title">'.$title.'</span>';
    $output .= '<span class="view_link">'.l("View video",'node/'.$nid).'</span></div>';
            
    return $output;
}
