<?php



/**
 * Implements hook_init().
 */
function mckc_omniture_init() {
  if(module_exists('sitecatalyst')){
    drupal_add_js('var omni_suit_id= "' . variable_get('omni_suit_id', '') . '";', 'inline');
    drupal_add_js(drupal_get_path('module', 'mckc_omniture') . '/omniture_js/custom_variables.js', array('scope' => 'footer', 'weight' => 10)); // adding last after omniture load js
  }
}


/**
 * Implements hook_form_alter().
 */
function mckc_omniture_form_alter(&$form, &$form_state, $form_id) {
  if( $form_id == 'sitecatalyst_admin_settings'){
    $form['omni_suit_id'] = array(
      '#type' => 'textfield',
      '#weight' => -100, 
      '#title' => t('Omniture suit id for this Instance or Site.'),
      '#description' => t('Example mckinseydev, mckinseyprod etc!'),
      '#default_value' => variable_get('omni_suit_id', ''),
    );
    $form['#submit'][] = 'mckc_omniture_settings_submit';
  }
}

/*
 Settings submission handler
*/
function mckc_omniture_settings_submit(&$form, &$form_state) {
  $omni_id = $form_state['values']['omni_suit_id'];
  if(!empty($omni_id)) {
    variable_set('omni_suit_id', $omni_id);
  }
}


/**
 * Implements hook_omniture_variables().
 */
function mckc_omniture_sitecatalyst_variables() {
  global $subsite_home_page_url;
  $variables = array();
  if(isset($_SERVER['HTTP_PERSON_ID'])) {
    $visitor_id = $_SERVER['HTTP_PERSON_ID'];
    $variables['s.prop1'] = $visitor_id;

    
    $omniture_settings = array(
      'pidX' => $visitor_id,
      'channel' => $subsite_home_page_url 
     );
    drupal_add_js(array('myOmniture' => $omniture_settings), 'setting');

    $uri = $_SERVER['REQUEST_URI'];
    $search = strpos($uri, 'search/site/');
    if ($search != false) {
      $search_term1 = explode('site/', $uri);
      $search_term2 = explode('?', $search_term1[1]);
      // passing search result key word
      $variables['s.prop4'] = $search_term2[0];
      $variables['s.prop3'] = $subsite_home_page_url;
    }
    return array('variables' => $variables);
  }
}
