<?php

/*
 * hook_init()
 */

global $library_subsite_variable;

$library_subsite_variable = array(
    'orginaction' =>
    array('to' => 'organization_practice_learning_team@mckinsey.com',
        'from_email' => 'organization_practice_learning_team@mckinsey.com',
        'subject' => 'Suggest a video',
        'msg' => 'I recommend adding the following video to the Org in Action video library',
        'site_name' => 'Org in Action',
         'tid'=>'455',
         'resource'=>'http://home.intranet.mckinsey.com/practicespaces/ps/org/',
        'recommend_text' => ' recommended an Org in Action video.'),
    'opsinaction' =>
    array('to' => 'global_ops_learning_team@mckinsey.com,Ops_Feedback@mckinsey.com',
        'from_email' => 'global_ops_learning_team@mckinsey.com',
        'subject' => 'Suggest a video',
        'msg' => 'I recommend adding the following video to the Ops in Action video library',
        'site_name' => 'Ops in Action',
        'tid'=>'456',
        'resource'=>'http://home.intranet.mckinsey.com/practicespaces/ps/ops/',
        'recommend_text' => ' recommended an Ops in Action video.'),
    'btoacademy' =>
    array('to' => 'bt_learning_registration@mckinsey.com',
        'from_email' => 'bt_learning_registration@mckinsey.com',
        'subject' => 'Suggest a video',
        'msg' => 'I recommend adding the following video to the BTO Academy video library',
        'site_name' => 'BTO Academy',
        'tid'=>'457',
        'resource'=>'http://home.intranet.mckinsey.com/practicespaces/ps/bt/',
        'recommend_text' => ' recommended a BTO Academy video.'),
    'miscellaneous' =>
    array('to' => '',
        'from_email' => '',
        'subject' => 'Suggest a video',
        'msg' => 'I recommend adding the following video to the miscellaneous library',
        'site_name' => 'Miscellaneous: Video Library',
        'tid'=>'536',
        'resource'=>'',
        'recommend_text' => ' recommended a Miscellaneous video.'),
        );

/**
 * Implements hook_block_info().
 */
function videolibrary_core_block_info() {
    $blocks = array();
    $blocks['site_switching'] = array(
        'info' => t('Video Library Site Switching Menu'),
    );
    $blocks['category_menu'] = array(
        'info' => t('Category Menu For All Library'),
    );

    return $blocks;
}

function videolibrary_core_block_view($delta = '') {
    switch ($delta) {
        case 'site_switching':
            $block['subject'] = null; // Most forms don't have a subject
//    $block['content'] = noti_block_view();
            $block['content'] = site_switching();
            break;
        case 'category_menu':
            $block['subject'] = null; // Most forms don't have a subject
//    $block['content'] = noti_block_view();
            $block['content'] = category_menu();
            break;
    }
    return $block;
}

/*
 *
 */

function site_switching() {
    $terms = taxonomy_get_tree(5);
    $content = '<ul class="sites_switch">';
    foreach ($terms as $val) {
        $content .='<li>' . l($val->name, $val->name . '') . '</li>';
    }
    $content .='</ul>';
    return $content;
}

/*
 * get term id from term name
 */

function get_term_id($name) {
    if ($name) {
        return db_query("SELECT tid FROM {taxonomy_term_data} WHERE name =:name and vid =:vid", array(':name' => $name, ':vid' => 5))->fetchField();
    }
}

/*
 * Category Menu For all Library
 */

function category_menu() {
    $argument = explode('/', request_path());
    global $subsite_home_page_url;
    $category_vocab = array('orginaction' => 'category', 'btoacademy' => 'bto_category', 'opsinaction' => 'ops_category');

    $homeclass = '';
    $tagsclass = '';
    $arg0 = $argument[0];
    $arg2 = arg(2);
    if ($arg0 == $subsite_home_page_url && arg(1) == '') {
        $homeclass = 'selected homepage_link';
    } elseif (arg(1) == 'tags') {
        $tagsclass = 'selected';
    } elseif (arg(1) == 'browse') {
        $homeclass = 'selected';
    }

    $vocab = $category_vocab[$arg0];
//#block-views-views-by-category-block .block-content.content .left-side-menu li.selected
    if ($vocab) {
        $browse_url = url("$arg0/browse");
        $tag_url = url("$arg0/tags");
        $content = '';
        $content .= '<div class="block view-views-by-category" id="block-views-views-by-category-block"><div class="block-content content"><div class="left-side-menu"><ul>
<li class="view-all ' . $homeclass . '"><a href="' . $browse_url . '">View All</a></li>
<li class="by-tags ' . $tagsclass . '"><a href="' . $tag_url . '">By Tags</a></li>
<li class="by-category">By Category</li></ul>';

        $query = db_query("SELECT taxonomy_term_data.name AS taxonomy_term_data_name, taxonomy_term_data.vid AS taxonomy_term_data_vid, taxonomy_term_data.tid AS tid, taxonomy_vocabulary.machine_name AS taxonomy_vocabulary_machine_name FROM
{taxonomy_term_data} taxonomy_term_data LEFT JOIN {taxonomy_vocabulary} taxonomy_vocabulary ON taxonomy_term_data.vid = taxonomy_vocabulary.vid WHERE (( (taxonomy_vocabulary.machine_name IN  ('$vocab')) ))")->fetchAll();
        $content .= '<ul class="category-list">';
        foreach ($query as $row) {
            if ($arg2 == $row->tid) {
                $content .='<li>' . l($row->taxonomy_term_data_name, 'taxonomy/term/' . $row->tid, array('attributes' => array('class' => array('active')))) . '</li>';
            } else {
                $content .='<li>' . l($row->taxonomy_term_data_name, 'taxonomy/term/' . $row->tid) . '</li>';
            }
        }
        $content .= '</ul></div></div></div>';
        return $content;
    }
}

function user_top_menu_link() {
    global $library_subsite_variable;
    global $subsite_home_page_url;
    global $user;
    $is_front = drupal_is_front_page();
    //if($is_front==TRUE) {
   /* if(!($subsite_home_page_url)) {
        $suggest='How to Suggest a Video';
    }
    else{
        $suggest='Suggest a Video';
    }*/
    $mail_to = $library_subsite_variable[$subsite_home_page_url]['to'];
    $subject = $library_subsite_variable[$subsite_home_page_url]['subject'];
    $msg = $library_subsite_variable[$subsite_home_page_url]['msg'];
    $content = '';
    $content .= '<div id="authorize"><ul class="user">';

    $profile_url = '';
    $role = 'contractor';
    if (in_array($role, array_values($user->roles))) {
        $profile_url = "http://home.intranet.mckinsey.com/ks/research/home/welcome";
    } else {
        $profile_url = 'http://home.intranet.mckinsey.com/profiles/people/' . $_SERVER['HTTP_VENDORID'];
    }
    if ($user->uid != 0) {
        $content .='<li class="first">' . t('Welcome ') . '<a href="' . $profile_url . '" target="_blank">' . $user->name . '</a></li>';
        $content .='<li class="second"><a href="' . url('newsletter/subscriptions') . '">My Notifications</a></li>';

        $adminRoles = array("orginaction"=>"org web master", "opsinaction"=> "ops web master", "btoacademy" => "bto web master" ,"admin"=>"administrator","super admin"=>"super admin");
        $device = array('ipad', 'iphone');
        foreach ($adminRoles as $value=>$role) {
            if (in_array($role, $user->roles) && !(bool) strpos($_SERVER['HTTP_USER_AGENT'], 'iPad') && !(bool) strpos($_SERVER['HTTP_USER_AGENT'], 'iPhone')) {
                    //$lib_name = $subsite_home_page_url;
                    //if($role=="super admin") {
                        $content .='<li class="third">' . l("Admin", "admin/dashboard") . '</li>';
                        break;
                        //break;
                    //}
                    //elseif($lib_name == $value OR $user->roles=='administrator') {
                        //$content .='<li class="third">' . l("Admin", "admin/dashboard/". $value) . '</li>';
                        //break;
                    //}
        }
        }
    } else {
        $content .='<li class="first"><a href="' . url('user') . '">' . t('Login') . '</a></li>';
    }
    $content .='
<li class="last hidden-phone"><a id="suggest-link" class="ctools-use-modal ctools-modal-modal-popup-medium" href="suggest/nojs">Suggest a Video</a></li>

<li class="feedback"><a href="mailto:?Subject=Feedback will be great&body=">
Feedback</a></li>
<li class="last"><a href="#">How to suggest a video</a>
<div class="modal">
  <div class="modal-header">
    <button type="button" class="close">&times;</button>
    <h3>How to suggest a video</h3>
  </div>
  <div class="modal-body">
    <p>For security reasons, you can only suggest a video from the desktop version of the video library. The link is located on the top navigation bar.</p>
  </div>
</li>
</ul>
<p class="copyright">&#169; 1996-' . $date = date("Y") . $date . ' McKinsey & Company</p></div>';
    return $content;
}

function videolibrary_core_views_api() {
    return array(
        'api' => 3,
    );
}

function videolibrary_core_views_query_alter(&$view, &$query) {
    if ($view->name == 'logging') {
        //dsm($query, 'before');
        // Adding OR condition for the contextual filters.
        $query->where[0]['type'] = 'OR';
        //dsm($query, 'after');
    }
}

function videolibrary_core_views_pre_render(&$view) {
  if($view->name=='global_popular_video') {
    // Get most popular from 1st library
    $result1 = $view->result;
    // Get most popular from 2nd library
    $result2 = views_get_view_result('global_popular_video', $display_id = 'block_1');
    // Get most popular from 3rd library
    $result3 = views_get_view_result('global_popular_video', $display_id = 'block_2');
    // Merge the result arrays
    $new_double = array_merge($result1, $result2);
    $new_triple = array_merge($new_double, $result3);
    // Final result array is a combination of the 2 libraries
    $view->result = $new_triple;
  }
}

function videolibrary_core_form_alter(&$form, &$form_state, $form_id) {
    if($form_id=='views_exposed_form') {
    $form['field_library_tid']['#options'][536] ='Miscellaneous';
    $form['field_library_tid']['#options'][457] ='BTO Academy';
    $form['field_library_tid']['#options'][456] ='Ops in Action';
    $form['field_library_tid']['#options'][455] ='Org in Action';
}
    if($form_id =='upload_video_node_form') {
        global $user;
    //    $orginaction =  "$form['field_library']['und']['#options'][455]";
        $library_roles = array(
            '455' => 'org web master' ,
            '456' => 'ops web master',
            '457' => 'bto web master'
             );
        $roles = user_roles();
        $current_user_role = $user->roles;
        $result = array_intersect($library_roles, $current_user_role);
        $result_count = count($result);
        if($result_count==1) {
            if(in_array('org web master', $current_user_role)) {
                unset($form['field_library']);
                unset($form['field_bto_category']);
                unset($form['field_bto_tags']);
                unset($form['field_ops_category']);
                unset($form['field_ops_tags']);
        }
            elseif(in_array('ops web master', $current_user_role)) {
                unset($form['field_library']);
                unset($form['field_bto_category']);
                unset($form['field_bto_tags']);
                unset($form['field_category']);
                unset($form['field_tags']);
        }
            elseif(in_array('bto web master', $current_user_role)) {
                unset($form['field_library']);
                unset($form['field_category']);
                unset($form['field_tags']);
                unset($form['field_ops_category']);
                unset($form['field_ops_tags']);
        }
    }elseif($result_count==2) {
        $diff= array_diff($library_roles,$result);
        foreach($diff as $key=>$value) {
            unset($form['field_library']['und']['#options'][$key]);
        }
}
else {
    return;
}
}

elseif ($form_id =='user_profile_form') {
    global $user;
    $current_user_roles = $user->roles;
    // Show all assignable roles to the super admin role
    if (!array_key_exists('8', $current_user_roles)) {
      $valid_roles = $form['account']['roleassign_roles']['#options'];
      unset($current_user_roles["2"]);
      $form['account']['roleassign_roles']['#options'] = $current_user_roles;
    }
  }
}

function videolibrary_core_custom_theme() {
    $current_path = explode('/', drupal_get_path_alias($_GET['q']));
    if(($current_path[1] == 'dashboard') && ($current_path[2]==('orginaction' OR 'btoacademy' OR 'opsinaction'))) {
    return variable_get('admin_theme');
}
}
/*
function videolibrary_core_menu_alter(&$items) {
        if(arg(0) == 'orginaction') {
    $items['admin/dashboard'] =;
}
}
*/

function videolibrary_core_node_view($node, $view_mode, $langcode) {
    if(($_SERVER['HTTP_REFERER']==NULL) && ($GLOBALS['_GET']['q'] == 'node/5')) {
    $flag = flag_get_flag('default');
    if($flag) {
    $libs=array('455'=>'orginaction','456'=>'opsinaction','457'=>'btoacademy');
    foreach($libs as $key=>$value) {
    if ($flag->is_flagged($key)) {
      drupal_goto($value);
    }
    }
}else {
    return;
}
}
}

function videolibrary_core_menu() {
    $items = array();

  $items['suggest/%ctools_js'] = array(
    'page callback' => 'videolibrary_core_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Ajax menu callback.
 */
function videolibrary_core_callback($ajax) {
  if ($ajax) {
    ctools_include('ajax');
    ctools_include('modal');

    $form_state = array(
      'ajax' => TRUE,
      'title' => t('Suggest a Video'),
    );

    // Use ctools to generate ajax instructions for the browser to create
    // a form in a modal popup.
    $output = ctools_modal_form_wrapper('videolibrary_core_form', $form_state);

    // If the form has been submitted, there may be additional instructions
    // such as dismissing the modal popup.
    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
    }

    // Return the ajax instructions to the browser via ajax_render().
    print ajax_render($output);
    drupal_exit();
  }
  else {
    return drupal_get_form('videolibrary_core_form');
  }
}
/**
 * Drupal form to be put in a modal.
 */
function videolibrary_core_form($form, $form_state) {
    global $library_subsite_variable;
    global $subsite_home_page_url;
    $mail_to_ = $library_subsite_variable[$subsite_home_page_url]['to'];
    $subject = $library_subsite_variable[$subsite_home_page_url]['subject'];
    $msg = $library_subsite_variable[$subsite_home_page_url]['msg'];
    $mail_to_bto = $library_subsite_variable['btoacademy']['to'];
    $subject_bto = $library_subsite_variable['btoacademy']['subject'];
    $msg_bto = $library_subsite_variable['btoacademy']['msg'];
    $mail_to_ops = $library_subsite_variable['opsinaction']['to'];
    $subject_ops = $library_subsite_variable['opsinaction']['subject'];
    $msg_ops = $library_subsite_variable['opsinaction']['msg'];
    $mail_to_org = $library_subsite_variable['orginaction']['to'];
    $subject_org = $library_subsite_variable['orginaction']['subject'];
    $msg_org = $library_subsite_variable['orginaction']['msg'];

  $form['lib_list']= array(
  '#type' => 'radios',
  '#title' => t('Choose library you want to suggest video.'),
  '#options' => array(0 => 'General', 1 => 'BTO Academy',2=>'Ops in Action',3=>'Org in Action'),
  '#required'=>TRUE
);
  $gen = ' <a class="lib" id="gen" href="mailto:' . $mail_to . '?Subject=' . $subject . '&body=' . $msg . '">General</a><br/>';
  $bto= ' <a class="lib" id="bto" href="mailto:' . $mail_to_bto . '?Subject=' . $subject_bto . '&body=' . $msg_bto . '">Bto Academy</a><br/>';
  $ops ='<a class="lib" id="ops" href="mailto:' . $mail_to_ops . '?Subject=' . $subject_ops . '&body=' . $msg_ops . '">Ops in action</a><br/>';
  $org= '<a class="lib" id="org" href="mailto:' . $mail_to_org . '?Subject=' . $subject_org . '&body=' . $msg_org . '">Org in Action</a>';


 $form['lib_list_gen'] = array(
    '#title' => t('Click below to suggest a video'),
    '#type' => 'item',
    '#markup'=> $gen,
    '#states' => array(
      'visible' => array(
        ':input[name="lib_list"]' => array('value' => '0'),
      ),
    ),
  );
 $form['lib_list_bto'] = array(
    '#title' => t('Click below to suggest a video'),
    '#type' => 'item',
    '#markup'=> $bto,
    '#states' => array(
      'visible' => array(
        ':input[name="lib_list"]' => array('value' => '1'),
      ),
    ),
  );
 $form['lib_list_ops'] = array(
    '#title' => t('Click below to suggest a video'),
    '#type' => 'item',
    '#markup'=> $ops,
    '#states' => array(
      'visible' => array(
        ':input[name="lib_list"]' => array('value' => '2'),
      ),
    ),
  );
 $form['lib_list_org'] = array(
    '#title' => t('Click below to suggest a video'),
    '#type' => 'item',
    '#markup'=> $org,
    '#states' => array(
      'visible' => array(
        ':input[name="lib_list"]' => array('value' => '3'),
      ),
    ),
  );
    return $form;
}
