<?php

/**
 * @file
 * Custom module to fetch data from ORS database.
 *
 * Provide the connectivity with ORS database
 * so admin can fetch data from ORS database like New Faces, Anniversary, Birthdays.
 */
class ORSDbHandler {

    private static $_ORSDBHandle;

    private function __construct() {

    }

    public static function getHandle() {
        if (!isset(self::$_ORSDBHandle)) {
            $username = variable_get('ors_database_username', 'username');
            $password = variable_get('ors_database_password', 'password');
            $connection_string = variable_get('ors_database_connection_string', '');
            self::$_ORSDBHandle = oci_connect($username, $password, "$connection_string");
        }
        return self::$_ORSDBHandle;
    }

}

global $mck_user;

/**
 * Implements hook_permission().
 */
function mck_ors_data_permission() {
    return array(
        'ors data update' => array(
            'title' => t('Ors data update'),
            'description' => t('Update ORS data'),
        ),
    );
}

/**
 * Implements hook_init().
 */
function mck_ors_data_init() {
    //print_r(node_load(8085));
}

/**
 * Implements hook_menu().
 */
function mck_ors_data_menu() {
    $items['admin/config/ors-data/ors-data-update'] = array(
        'title' => 'ORS Data',
        'page callback' => 'mck_ors_data_ors_data_page',
        'page arguments' => array('mck_ors_data_ors_data_update_people_form', 'mck_ors_data_ors_data_settings_form'),
        'access arguments' => array('ors data update'),
        'file' => 'mck_ors_data.admin.inc',
    );

    $items['ors_user/fetch'] = array(
        'page callback' => 'ors_fetch_users',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

/**
 * Implements hook_block_info().
 */
function mck_ors_data_block_info() {
    $blocks = array();
    $blocks['ors_user_fetch'] = array(
        'info' => t('Ors User Fetch'),
        'weight' => '99',
    );

    return $blocks;
}

function mck_ors_data_block_view($delta = '') {
    switch ($delta) {
        case 'ors_user_fetch':
            $block['subject'] = null; // Most forms don't have a subject
            $block['content'] = ors_fetch_user_link();
            break;
    }
    return $block;
}

function ors_fetch_user_link() {
  return '<ul><li>' . l('PDIX User Conversion Report', 'ors_user/fetch') . '</li></ul>';
}

/*
 * ORS connect handler return ORS object if things goes fine.
 */

function get_ors_connection() {
    try {
        if (function_exists('oci_connect')) {
            $c = ORSDbHandler::getHandle();
            if (!$c) {
                drupal_set_message(t('Unable to connect check settings.'), 'warning');
                return '';
            } else {
                return $c;
            }
        } else {
            drupal_set_message(t('oci_connect function not existes. oci8 php extension is not installed or enabled.'), 'warning', FALSE);
            return '';
        }
    } catch (Exception $e) {
        drupal_set_message(t('Exception'), 'status', FALSE);
        drupal_set_message(t('Message: ' . $e->getMessage()), 'status', FALSE);
    }
}

/*
  Get people from ORS database
 */

function ors_fetch_users() {
    $connection = get_ors_connection();

    $query = "SELECT PERSON_ID,FMNO,ADS_LOGIN_NAME
FROM psn_person where person_status = 'Active'";

    $stid = oci_parse($connection, $query);
    $execute = oci_execute($stid);
    $row_count = ocirowcount($stid);
    // if records are in connection
    if (sizeof(oci_fetch_array($stid, OCI_RETURN_NULLS + OCI_ASSOC)) > 0) {

            $content = '';
    $content .= '<table id="csvtable">
 <thead><tr><th>' . t('PERSON_ID') . '</th><th>' . t('FMNO') . '</th><th>' . t('ADS_LOGIN_NAME') . '</th></tr></thead>
<tbody>';

        // create or update people
        while ($row = oci_fetch_array($stid, OCI_RETURN_NULLS + OCI_ASSOC)) {
            $row = array_change_key_case($row, CASE_LOWER); //convert field to lowercase
            //check if node already there in database
            //$content[] = $row;
            $content .= '<tr><td>' . $row['person_id'] . '</td><td>' . $row['fmno'] . '</td><td>' . $row['ads_login_name'] . '</td> </tr>';
        }
        $content .= '<tbody></table>';
        header('Content-type: application/vnd.ms-excel');
        header("Content-Disposition: attachment; filename=test.xls");
        header("Pragma: no-cache");
        header("Expires: 0");
        echo $content;
        exit;
    }
}


function ors_fetch_users_role($pid_ors) {
    print "fetch users";
    $connection = get_ors_connection();

    $query = "select * from VW_APP_AUTHENTICATE where person_id = '" . $pid_ors . "'";
     
// where person_id = '" . $pid_ors . "'";

// $query = "select position_group from VW_APP_AUTHENTICATE
// where person_id = '10018326969'";
print_r($query);

    $stid = oci_parse($connection, $query);
    $execute = oci_execute($stid);
    print "execute ends";
    $row_count = ocirowcount($stid); //This will not work though
    
    // if records are in connection fetch all the records and store in an array $data
    $data = oci_fetch_array($stid, OCI_RETURN_NULLS + OCI_ASSOC);
    if(!empty($data)) {
        $ors_data = array_change_key_case($data, CASE_LOWER);
        return $data;
    }
}
